### ISSUE TITLE
How to model behaviors that can only be sampled asynchronously

### ISSUE THREAD

**Issue by masaeedu** [funkia/hareactive#38]
Consider a "behavior" such as the state of some data on a remote system (perhaps accessible via a REST API). The state exists at all points in time, but in order to access it locally I need to communicate asynchronously with the remote machine over the network. 

In something like rxjs, I don't really have a choice: everything must be modeled as a stream. I'd probably do something like `const req = new Subject(); const responses = req.flatMap(_ => updateState()).publish()`, subscribe my response handling to `responses`, and do `req.next()` whenever I want to update the remote state. Or perhaps something simpler, like `Observable.interval(1000).flatMap(_ => updateState())`, although this is worse for granularity.

So in hareactive, do I model this kind of thing as a `Behavior<Future<TState>>` or something?

**Comment by paldepind** [comment]
Hello @masaeedu. I apologize for the late response. That is a very good question.

You can definitely do something similar to the approach you're describing with RxJS. Start with a `Stream`, map it to a stream of requests and then merge it to a behavior in the end. Here is some pseudocode:

```
// get a stream of requests
someStream.map(doRequest);
// run the side-effects
performStream(requests);
// and convert it to a behavior
stepper(initialValue, requestResults);
```

That may be the best way to do it. Since the example you're describing uses HTTP it's not possible for the remote machine to push changes to the client. The client will have to poll regularly. How often would you ideally want this polling to happen? Every n'th seconds? Or whenever something particularly happens in the app?

One problem with regards to behaviors that can only be sampled asynchronously is with functions like [`snapshot`](https://github.com/funkia/hareactive#snapshotbb-behaviorb-s-streamany-streamb). `snapshot` needs the value at a behavior exactly when some event occurs on a stream. This is not possible if the behavior cannot be sampled synchronously.

But, I @limemloh has been working on and thinking about how to support asynchronous behaviors anyway. I think it would be very helpful if you would describe what your ideal solution would be? Are you happy with the RxJS-like solution? Or do you imagine a better way to do it?
