### ISSUE TITLE
FP newbie question about library implementation

### ISSUE THREAD

**Issue by FbN** [funkia/hareactive#60]
I'm a newbie to FP (with a background 10+ years in OOP). Researching the various library/framework available I have approaded to this repository which I find really interesting and divulgative. This library and Turbine looks like a more interesting approach than cycle js for example.

The question is about library implementation.

I see you have user class and hereditariaty to implement your data structures with abbondand use of the 'this' keyword. So I suppose the library is developed in OOP, or I mistaking something? 

If yes is not a controsense to implement a FP library using OOP?

Thanks in advance for the explanation and compliments for the great work.

**Comment by paldepind** [comment]
Are you still interested in an answer @FbN? :smile:

**Comment by FbN** [comment]
I think to have the answer but you can confirm my idea. It's not bad to use
classes for data structures as long you have no method's that mutate
internal state but return a new instance of the structure (or other data)
without side effects.
But use static functions instead of class methods can make easies to do dot
free functions composition (versus dot style concatenation).

Il dom 28 lug 2019, 17:21 Simon Friis Vindum <notifications@github.com> ha
scritto:

**Comment by paldepind** [comment]
Yes, you are right. One could say that as long as a class doesn't mutate its properties and as long as it's methods are pure then one is operating in an intersection between OOP and purely functional programming.

There are some functional programming fans who don't like methods at all. In my mind, a pure method is just a function which you call with a slightly different syntax. And sometimes chaining can be really nice. Therefore Hareactive offers some pure methods for people who like that :smile:

But, there are actually a few additional reasons as well.

One of them is that the implementation of Hareactive relies heavily on polymorphism. We have a `Behavior` abstract class and then we have many subclasses which extends this class. For each of the primitive operators, there is a class: `MapBehavior`, `ScanBehavior`, `FlatMapBehavior`, and so on. That is because some operations depend on what type of behavior one is dealing with. For instance, when we want to update the value of a `MapBehavior` we have to do something different than for a `ScanBehavior`. We achieve this by letting each behavior class implement a bunch of methods. I'm sure you're very familiar with this from your OOP experience. Calling `cat.talk()` on a `Cat` does something different than calling `dog.talk()` on a `Dog` :wink:.

Many functional programming languages has a replacement for this form of polymorphism called "type classes". But, we're implementing Hareactive in TypeScript so we can't use this more "functional" approach. Hence we're using clases. We could have avoided classes though. There are other options in JavaScript, but, they would all involve putting properties on objects in some form. But, classes is often the best way to do that in JavaScript IMO. Especially because performance is usually good, we get to leverage the `class` syntax, and the types are easy to get right in TypeScript.

I hope that answers you question somewhat :)

> Researching the various library/framework available I have approaded to this repository which I find really interesting and divulgative. This library and Turbine looks like a more interesting approach than cycle js for example.

I'm happy to hear that :smile: It'd be very interested in hearing what made you interested in Turbine? Also, what parts of Turbine did you not like? Turbine is not the easiest framework to understand if one is not experienced with functional programming. Where there anything that you found particularly confusing?
